title: Summer School on ML for EM
nav_title: Summer School on ML for EM
tagline: 


event_date: TBA
registration_opens_date: TBA
registration_closes_date: TBA

author:
mailbox_address:

# description: |
#   Conference workshop on Atomic Fabrication

url: "https://kaliningroup.github.io/summer_school/"
github_repo: kaliningroup

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - index.md
  - program.md
  - history.md
  - feedback.md
  - resources.md
  - map.md
  - about.md
  - faq.md


# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: soon

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: open

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"


# Hide the GitHub footer links
gh_edit_link: false       # removes "Improve this page" / "Edit this page"
gh_source_link: false     # if your theme version supports it, hides "View page source"
last_edit_timestamp: false
